#!/bin/bash
#SETMAIL7
#Coded by Z3R07-RED 2021

function internet_connection(){
curl -I "www.google.es" &> /dev/null
if [[ $? -eq 0 ]]; then
    echo ""
else
    echo $(clear)
    echo -e "${R}[INTERNET]:${M} Not connected!${W}"
    echo ""; exit 1
fi
}

function randsetmaildata(){
        MATRIX="abcdefghijklmnopqrstuvwxyzABCDEFGHIJLKMNOPQRSTUVWXYZ-0123456789"
        Z3R07=""
        n=1
        i=1
        [ -z "$1" ] && length=8 || length=$1
        [ -z "$2" ] && num=1 || num=$2
        while [ ${i} -le $num ]; do
                while [ ${n} -le $length ]; do
                        Z3R07="$Z3R07${MATRIX:$(($RANDOM%${#MATRIX})):1}"
                        n=$(($n + 1))
                done
                echo $Z3R07
                n=1
                Z3R07=""
                i=$(($i + 1))
        done
}


